### ISSUE TITLE
Trouble with setup

### ISSUE THREAD

**Issue by macrospecter** [giovannicoppola/alfred-yaanki#4]
This workflow looks really promising. However, I can't seem to get the setup to work correctly. 

The biggest issue is that when I create a card I get an error on the Anki side. I can always see that the card I've added through the workflow has in fact been added to the database, but then when I click on the card to open it I get this message: "Anki encountered a problem. Please follow the troubleshooting steps." I have to delete the card in order to get Anki to start working again. 

The secondary issue is that I get the message that the database is "locked" when I try to select the decks to include in search through "yaanki: decks."

**Comment by giovannicoppola** [comment]
@macrospecter because they read the same database, anki needs to be completely closed for `alfred-yaanki` to work.

**Comment by macrospecter** [comment]
Yes, I did see that. And I make sure that I quit Anki before running the workflow. The problem is just that when I open up Anki to look at or study the cards I've made with the workflow, that's when I get the error and the cards are not readable (I can see the front side sitting in the database, but I cannot click on to read the full card without getting the error).

**Comment by macrospecter** [comment]
For what it's worth, the "locked" database issue seems to have solved itself. 

However, I still can't get the card-creating function to work. I'm still getting an error whenever I open the Anki database after creating a new card, or after clicking on the created card in the database, and I'm posting the debugging info below. 

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-13.4-x86_64-i386-64bit

Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.utils", line 1204, in <lambda>
  File "aqt.browser.browser", line 555, in on_all_or_selected_rows_changed
  File "aqt.editor", line 531, in set_note
  File "aqt.editor", line 544, in loadNote
  File "anki.notes", line 150, in items
  File "anki.notes", line 150, in <listcomp>
IndexError: list index out of range

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiConnect ['2055492159', 2024-01-21T14:03, 'None', '']
